development:
  adapter: postgresql
  encoding: unicode
  database: trademe_development
  pool: 5
  host: localhost
  username: trademe_postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: trademe_test
  pool: 5
  host: localhost
  username: trademe_postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: trademe_production
  pool: 5
  host: localhost
  username: trademe_postgres
  password: